# 
# Database Config
# =================
# 
# Replace the values here with your config, then copy to config/database.yml
# 
default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: root
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: taproot_development

test:
  <<: *default
  database: taproot_test
