# 
# This file is for storing NON-SENSITIVE settings.
#
# Values here are loaded into the SETTINGS constant. For example, below you can
# access "Hello" through SETTINGS['say']['hello']
#
development: &default
  transform_u_fitness:
    social:
      facebook: "https://www.facebook.com/SetaPersonalTraining"
      twitter: "https://twitter.com/TrainerMike28"
      youtube: "http://www.youtube.com/user/MikeSetaPT"

test:
  <<: *default

production:
  <<: *default
